/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LaporanBulanan {
  'tahun' : bigint,
  'pengeluaran' : Array<Pengeluaran>,
  'totalPengeluaran' : bigint,
  'pengeluaranPerKategori' : Array<[string, bigint]>,
  'transaksi' : Array<TransaksiSelesai>,
  'totalPemasukan' : bigint,
  'bulan' : bigint,
  'pendapatanBersih' : bigint,
}
export interface LaporanHarian {
  'pengeluaran' : Array<Pengeluaran>,
  'totalPengeluaran' : bigint,
  'transaksi' : Array<TransaksiSelesai>,
  'totalPemasukan' : bigint,
  'pendapatanBersih' : bigint,
}
export interface Pengeluaran {
  'jumlah' : bigint,
  'tanggal' : Time,
  'userId' : [] | [Principal],
  'deskripsi' : string,
  'kategori' : string,
  'waktu' : Time,
  'catatan' : [] | [string],
}
export interface RingkasanDashboard {
  'jumlahTransaksiBulanan' : bigint,
  'totalPengeluaranBulanan' : bigint,
  'jumlahTransaksiHarian' : bigint,
  'pendapatanBersihBulanan' : bigint,
  'totalPengeluaranHarian' : bigint,
  'pengeluaranPerKategoriHarian' : Array<[string, bigint]>,
  'pendapatanBersihHarian' : bigint,
  'pengeluaranPerKategoriBulanan' : Array<[string, bigint]>,
  'totalPemasukanHarian' : bigint,
  'totalPemasukanBulanan' : bigint,
}
export interface RingkasanDashboardMultiDevice {
  'userId' : Principal,
  'ringkasan' : RingkasanDashboard,
}
export type Time = bigint;
export interface Transaksi {
  'jumlah' : bigint,
  'harga' : bigint,
  'namaProduk' : string,
  'subtotal' : bigint,
}
export interface TransaksiSelesai {
  'total' : bigint,
  'userId' : [] | [Principal],
  'jumlahPembayaran' : [] | [bigint],
  'waktuTransaksi' : Time,
  'waktuPencatatan' : Time,
  'tanggalTransaksi' : Time,
  'kembalian' : [] | [bigint],
  'items' : Array<Transaksi>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPengeluaran' : ActorMethod<[], Array<Pengeluaran>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLaporanBulanan' : ActorMethod<[Time], LaporanBulanan>,
  'getLaporanBulananByUser' : ActorMethod<[Time, Principal], LaporanBulanan>,
  'getPengeluaranBulanan' : ActorMethod<[Time], Array<Pengeluaran>>,
  'getPengeluaranBulananByUser' : ActorMethod<
    [Time, Principal],
    Array<Pengeluaran>
  >,
  'getPengeluaranBulananLaporan' : ActorMethod<[Time], LaporanBulanan>,
  'getPengeluaranByKategori' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getPengeluaranHarian' : ActorMethod<[Time], LaporanHarian>,
  'getRingkasanDashboard' : ActorMethod<[], RingkasanDashboard>,
  'getRingkasanDashboardMultiDevice' : ActorMethod<
    [],
    Array<RingkasanDashboardMultiDevice>
  >,
  'getRiwayatTransaksi' : ActorMethod<[Time], Array<TransaksiSelesai>>,
  'getTotalTransaksi' : ActorMethod<[], Array<TransaksiSelesai>>,
  'getTransactionById' : ActorMethod<[string], TransaksiSelesai>,
  'getTransaksiHarian' : ActorMethod<[Time], LaporanHarian>,
  'getTransaksiHarianByUser' : ActorMethod<[Time, Principal], LaporanHarian>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLoggedIn' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'tambahPengeluaran' : ActorMethod<
    [string, string, bigint, Time, [] | [string]],
    undefined
  >,
  'tambahTransaksi' : ActorMethod<
    [Time, Array<Transaksi>, [] | [bigint], [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];