/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Pengeluaran = IDL.Record({
  'jumlah' : IDL.Nat,
  'tanggal' : Time,
  'userId' : IDL.Opt(IDL.Principal),
  'deskripsi' : IDL.Text,
  'kategori' : IDL.Text,
  'waktu' : Time,
  'catatan' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Transaksi = IDL.Record({
  'jumlah' : IDL.Nat,
  'harga' : IDL.Nat,
  'namaProduk' : IDL.Text,
  'subtotal' : IDL.Nat,
});
export const TransaksiSelesai = IDL.Record({
  'total' : IDL.Nat,
  'userId' : IDL.Opt(IDL.Principal),
  'jumlahPembayaran' : IDL.Opt(IDL.Nat),
  'waktuTransaksi' : Time,
  'waktuPencatatan' : Time,
  'tanggalTransaksi' : Time,
  'kembalian' : IDL.Opt(IDL.Nat),
  'items' : IDL.Vec(Transaksi),
});
export const LaporanBulanan = IDL.Record({
  'tahun' : IDL.Nat,
  'pengeluaran' : IDL.Vec(Pengeluaran),
  'totalPengeluaran' : IDL.Nat,
  'pengeluaranPerKategori' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'transaksi' : IDL.Vec(TransaksiSelesai),
  'totalPemasukan' : IDL.Nat,
  'bulan' : IDL.Nat,
  'pendapatanBersih' : IDL.Nat,
});
export const LaporanHarian = IDL.Record({
  'pengeluaran' : IDL.Vec(Pengeluaran),
  'totalPengeluaran' : IDL.Nat,
  'transaksi' : IDL.Vec(TransaksiSelesai),
  'totalPemasukan' : IDL.Nat,
  'pendapatanBersih' : IDL.Nat,
});
export const RingkasanDashboard = IDL.Record({
  'jumlahTransaksiBulanan' : IDL.Nat,
  'totalPengeluaranBulanan' : IDL.Nat,
  'jumlahTransaksiHarian' : IDL.Nat,
  'pendapatanBersihBulanan' : IDL.Nat,
  'totalPengeluaranHarian' : IDL.Nat,
  'pengeluaranPerKategoriHarian' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'pendapatanBersihHarian' : IDL.Nat,
  'pengeluaranPerKategoriBulanan' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalPemasukanHarian' : IDL.Nat,
  'totalPemasukanBulanan' : IDL.Nat,
});
export const RingkasanDashboardMultiDevice = IDL.Record({
  'userId' : IDL.Principal,
  'ringkasan' : RingkasanDashboard,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPengeluaran' : IDL.Func([], [IDL.Vec(Pengeluaran)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLaporanBulanan' : IDL.Func([Time], [LaporanBulanan], ['query']),
  'getLaporanBulananByUser' : IDL.Func(
      [Time, IDL.Principal],
      [LaporanBulanan],
      ['query'],
    ),
  'getPengeluaranBulanan' : IDL.Func([Time], [IDL.Vec(Pengeluaran)], ['query']),
  'getPengeluaranBulananByUser' : IDL.Func(
      [Time, IDL.Principal],
      [IDL.Vec(Pengeluaran)],
      ['query'],
    ),
  'getPengeluaranBulananLaporan' : IDL.Func(
      [Time],
      [LaporanBulanan],
      ['query'],
    ),
  'getPengeluaranByKategori' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPengeluaranHarian' : IDL.Func([Time], [LaporanHarian], ['query']),
  'getRingkasanDashboard' : IDL.Func([], [RingkasanDashboard], ['query']),
  'getRingkasanDashboardMultiDevice' : IDL.Func(
      [],
      [IDL.Vec(RingkasanDashboardMultiDevice)],
      ['query'],
    ),
  'getRiwayatTransaksi' : IDL.Func(
      [Time],
      [IDL.Vec(TransaksiSelesai)],
      ['query'],
    ),
  'getTotalTransaksi' : IDL.Func([], [IDL.Vec(TransaksiSelesai)], ['query']),
  'getTransactionById' : IDL.Func([IDL.Text], [TransaksiSelesai], ['query']),
  'getTransaksiHarian' : IDL.Func([Time], [LaporanHarian], ['query']),
  'getTransaksiHarianByUser' : IDL.Func(
      [Time, IDL.Principal],
      [LaporanHarian],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hapusTransaksi' : IDL.Func([Time], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLoggedIn' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'tambahPengeluaran' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'tambahTransaksi' : IDL.Func(
      [Time, IDL.Vec(Transaksi), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Pengeluaran = IDL.Record({
    'jumlah' : IDL.Nat,
    'tanggal' : Time,
    'userId' : IDL.Opt(IDL.Principal),
    'deskripsi' : IDL.Text,
    'kategori' : IDL.Text,
    'waktu' : Time,
    'catatan' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Transaksi = IDL.Record({
    'jumlah' : IDL.Nat,
    'harga' : IDL.Nat,
    'namaProduk' : IDL.Text,
    'subtotal' : IDL.Nat,
  });
  const TransaksiSelesai = IDL.Record({
    'total' : IDL.Nat,
    'userId' : IDL.Opt(IDL.Principal),
    'jumlahPembayaran' : IDL.Opt(IDL.Nat),
    'waktuTransaksi' : Time,
    'waktuPencatatan' : Time,
    'tanggalTransaksi' : Time,
    'kembalian' : IDL.Opt(IDL.Nat),
    'items' : IDL.Vec(Transaksi),
  });
  const LaporanBulanan = IDL.Record({
    'tahun' : IDL.Nat,
    'pengeluaran' : IDL.Vec(Pengeluaran),
    'totalPengeluaran' : IDL.Nat,
    'pengeluaranPerKategori' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'transaksi' : IDL.Vec(TransaksiSelesai),
    'totalPemasukan' : IDL.Nat,
    'bulan' : IDL.Nat,
    'pendapatanBersih' : IDL.Nat,
  });
  const LaporanHarian = IDL.Record({
    'pengeluaran' : IDL.Vec(Pengeluaran),
    'totalPengeluaran' : IDL.Nat,
    'transaksi' : IDL.Vec(TransaksiSelesai),
    'totalPemasukan' : IDL.Nat,
    'pendapatanBersih' : IDL.Nat,
  });
  const RingkasanDashboard = IDL.Record({
    'jumlahTransaksiBulanan' : IDL.Nat,
    'totalPengeluaranBulanan' : IDL.Nat,
    'jumlahTransaksiHarian' : IDL.Nat,
    'pendapatanBersihBulanan' : IDL.Nat,
    'totalPengeluaranHarian' : IDL.Nat,
    'pengeluaranPerKategoriHarian' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'pendapatanBersihHarian' : IDL.Nat,
    'pengeluaranPerKategoriBulanan' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalPemasukanHarian' : IDL.Nat,
    'totalPemasukanBulanan' : IDL.Nat,
  });
  const RingkasanDashboardMultiDevice = IDL.Record({
    'userId' : IDL.Principal,
    'ringkasan' : RingkasanDashboard,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPengeluaran' : IDL.Func([], [IDL.Vec(Pengeluaran)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLaporanBulanan' : IDL.Func([Time], [LaporanBulanan], ['query']),
    'getLaporanBulananByUser' : IDL.Func(
        [Time, IDL.Principal],
        [LaporanBulanan],
        ['query'],
      ),
    'getPengeluaranBulanan' : IDL.Func(
        [Time],
        [IDL.Vec(Pengeluaran)],
        ['query'],
      ),
    'getPengeluaranBulananByUser' : IDL.Func(
        [Time, IDL.Principal],
        [IDL.Vec(Pengeluaran)],
        ['query'],
      ),
    'getPengeluaranBulananLaporan' : IDL.Func(
        [Time],
        [LaporanBulanan],
        ['query'],
      ),
    'getPengeluaranByKategori' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPengeluaranHarian' : IDL.Func([Time], [LaporanHarian], ['query']),
    'getRingkasanDashboard' : IDL.Func([], [RingkasanDashboard], ['query']),
    'getRingkasanDashboardMultiDevice' : IDL.Func(
        [],
        [IDL.Vec(RingkasanDashboardMultiDevice)],
        ['query'],
      ),
    'getRiwayatTransaksi' : IDL.Func(
        [Time],
        [IDL.Vec(TransaksiSelesai)],
        ['query'],
      ),
    'getTotalTransaksi' : IDL.Func([], [IDL.Vec(TransaksiSelesai)], ['query']),
    'getTransactionById' : IDL.Func([IDL.Text], [TransaksiSelesai], ['query']),
    'getTransaksiHarian' : IDL.Func([Time], [LaporanHarian], ['query']),
    'getTransaksiHarianByUser' : IDL.Func(
        [Time, IDL.Principal],
        [LaporanHarian],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hapusTransaksi' : IDL.Func([Time], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLoggedIn' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'tambahPengeluaran' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'tambahTransaksi' : IDL.Func(
        [Time, IDL.Vec(Transaksi), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };