/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface RingkasanDashboardMultiDevice {
    userId: Principal;
    ringkasan: RingkasanDashboard;
}
export interface RingkasanDashboard {
    jumlahTransaksiBulanan: bigint;
    totalPengeluaranBulanan: bigint;
    jumlahTransaksiHarian: bigint;
    pendapatanBersihBulanan: bigint;
    totalPengeluaranHarian: bigint;
    pengeluaranPerKategoriHarian: Array<[string, bigint]>;
    pendapatanBersihHarian: bigint;
    pengeluaranPerKategoriBulanan: Array<[string, bigint]>;
    totalPemasukanHarian: bigint;
    totalPemasukanBulanan: bigint;
}
export interface Transaksi {
    jumlah: bigint;
    harga: bigint;
    namaProduk: string;
    subtotal: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Pengeluaran {
    jumlah: bigint;
    tanggal: Time;
    userId?: Principal;
    deskripsi: string;
    kategori: string;
    waktu: Time;
    catatan?: string;
}
export interface LaporanHarian {
    pengeluaran: Array<Pengeluaran>;
    totalPengeluaran: bigint;
    transaksi: Array<TransaksiSelesai>;
    totalPemasukan: bigint;
    pendapatanBersih: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LaporanBulanan {
    tahun: bigint;
    pengeluaran: Array<Pengeluaran>;
    totalPengeluaran: bigint;
    pengeluaranPerKategori: Array<[string, bigint]>;
    transaksi: Array<TransaksiSelesai>;
    totalPemasukan: bigint;
    bulan: bigint;
    pendapatanBersih: bigint;
}
export interface UserProfile {
    name: string;
}
export interface TransaksiSelesai {
    total: bigint;
    userId?: Principal;
    jumlahPembayaran?: bigint;
    waktuTransaksi: Time;
    waktuPencatatan: Time;
    tanggalTransaksi: Time;
    kembalian?: bigint;
    items: Array<Transaksi>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllPengeluaran(): Promise<Array<Pengeluaran>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLaporanBulanan(timestamp: Time): Promise<LaporanBulanan>;
    getLaporanBulananByUser(timestamp: Time, user: Principal): Promise<LaporanBulanan>;
    getPengeluaranBulanan(timestamp: Time): Promise<Array<Pengeluaran>>;
    getPengeluaranBulananByUser(timestamp: Time, user: Principal): Promise<Array<Pengeluaran>>;
    getPengeluaranBulananLaporan(timestamp: Time): Promise<LaporanBulanan>;
    getPengeluaranByKategori(bulan: bigint): Promise<Array<[string, bigint]>>;
    getPengeluaranHarian(timestamp: Time): Promise<LaporanHarian>;
    getRingkasanDashboard(): Promise<RingkasanDashboard>;
    getRingkasanDashboardMultiDevice(): Promise<Array<RingkasanDashboardMultiDevice>>;
    getRiwayatTransaksi(hari: Time): Promise<Array<TransaksiSelesai>>;
    getTotalTransaksi(): Promise<Array<TransaksiSelesai>>;
    getTransactionById(_id: string): Promise<TransaksiSelesai>;
    getTransaksiHarian(timestamp: Time): Promise<LaporanHarian>;
    getTransaksiHarianByUser(timestamp: Time, user: Principal): Promise<LaporanHarian>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isLoggedIn(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    tambahPengeluaran(kategori: string, deskripsi: string, jumlah: bigint, tanggal: Time, catatan: string | null): Promise<void>;
    tambahTransaksi(tanggalTransaksiItem: Time, items: Array<Transaksi>, jumlahPembayaran: bigint | null, kembalian: bigint | null): Promise<void>;
}
import type { LaporanBulanan as _LaporanBulanan, LaporanHarian as _LaporanHarian, Pengeluaran as _Pengeluaran, Time as _Time, Transaksi as _Transaksi, TransaksiSelesai as _TransaksiSelesai, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllPengeluaran(): Promise<Array<Pengeluaran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPengeluaran();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPengeluaran();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLaporanBulanan(arg0: Time): Promise<LaporanBulanan> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaporanBulanan(arg0);
                return from_candid_LaporanBulanan_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaporanBulanan(arg0);
            return from_candid_LaporanBulanan_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLaporanBulananByUser(arg0: Time, arg1: Principal): Promise<LaporanBulanan> {
        if (this.processError) {
            try {
                const result = await this.actor.getLaporanBulananByUser(arg0, arg1);
                return from_candid_LaporanBulanan_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLaporanBulananByUser(arg0, arg1);
            return from_candid_LaporanBulanan_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengeluaranBulanan(arg0: Time): Promise<Array<Pengeluaran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengeluaranBulanan(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengeluaranBulanan(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengeluaranBulananByUser(arg0: Time, arg1: Principal): Promise<Array<Pengeluaran>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengeluaranBulananByUser(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengeluaranBulananByUser(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengeluaranBulananLaporan(arg0: Time): Promise<LaporanBulanan> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengeluaranBulananLaporan(arg0);
                return from_candid_LaporanBulanan_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengeluaranBulananLaporan(arg0);
            return from_candid_LaporanBulanan_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengeluaranByKategori(arg0: bigint): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengeluaranByKategori(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengeluaranByKategori(arg0);
            return result;
        }
    }
    async getPengeluaranHarian(arg0: Time): Promise<LaporanHarian> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengeluaranHarian(arg0);
                return from_candid_LaporanHarian_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengeluaranHarian(arg0);
            return from_candid_LaporanHarian_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRingkasanDashboard(): Promise<RingkasanDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getRingkasanDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRingkasanDashboard();
            return result;
        }
    }
    async getRingkasanDashboardMultiDevice(): Promise<Array<RingkasanDashboardMultiDevice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRingkasanDashboardMultiDevice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRingkasanDashboardMultiDevice();
            return result;
        }
    }
    async getRiwayatTransaksi(arg0: Time): Promise<Array<TransaksiSelesai>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiwayatTransaksi(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiwayatTransaksi(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalTransaksi(): Promise<Array<TransaksiSelesai>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalTransaksi();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalTransaksi();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionById(arg0: string): Promise<TransaksiSelesai> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionById(arg0);
                return from_candid_TransaksiSelesai_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionById(arg0);
            return from_candid_TransaksiSelesai_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaksiHarian(arg0: Time): Promise<LaporanHarian> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaksiHarian(arg0);
                return from_candid_LaporanHarian_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaksiHarian(arg0);
            return from_candid_LaporanHarian_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaksiHarianByUser(arg0: Time, arg1: Principal): Promise<LaporanHarian> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaksiHarianByUser(arg0, arg1);
                return from_candid_LaporanHarian_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaksiHarianByUser(arg0, arg1);
            return from_candid_LaporanHarian_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isLoggedIn(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLoggedIn();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLoggedIn();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async tambahPengeluaran(arg0: string, arg1: string, arg2: bigint, arg3: Time, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.tambahPengeluaran(arg0, arg1, arg2, arg3, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tambahPengeluaran(arg0, arg1, arg2, arg3, to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async tambahTransaksi(arg0: Time, arg1: Array<Transaksi>, arg2: bigint | null, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.tambahTransaksi(arg0, arg1, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.tambahTransaksi(arg0, arg1, to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_LaporanBulanan_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LaporanBulanan): LaporanBulanan {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LaporanHarian_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LaporanHarian): LaporanHarian {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Pengeluaran_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pengeluaran): Pengeluaran {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TransaksiSelesai_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransaksiSelesai): TransaksiSelesai {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jumlah: bigint;
    tanggal: _Time;
    userId: [] | [Principal];
    deskripsi: string;
    kategori: string;
    waktu: _Time;
    catatan: [] | [string];
}): {
    jumlah: bigint;
    tanggal: Time;
    userId?: Principal;
    deskripsi: string;
    kategori: string;
    waktu: Time;
    catatan?: string;
} {
    return {
        jumlah: value.jumlah,
        tanggal: value.tanggal,
        userId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.userId)),
        deskripsi: value.deskripsi,
        kategori: value.kategori,
        waktu: value.waktu,
        catatan: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.catatan))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tahun: bigint;
    pengeluaran: Array<_Pengeluaran>;
    totalPengeluaran: bigint;
    pengeluaranPerKategori: Array<[string, bigint]>;
    transaksi: Array<_TransaksiSelesai>;
    totalPemasukan: bigint;
    bulan: bigint;
    pendapatanBersih: bigint;
}): {
    tahun: bigint;
    pengeluaran: Array<Pengeluaran>;
    totalPengeluaran: bigint;
    pengeluaranPerKategori: Array<[string, bigint]>;
    transaksi: Array<TransaksiSelesai>;
    totalPemasukan: bigint;
    bulan: bigint;
    pendapatanBersih: bigint;
} {
    return {
        tahun: value.tahun,
        pengeluaran: from_candid_vec_n10(_uploadFile, _downloadFile, value.pengeluaran),
        totalPengeluaran: value.totalPengeluaran,
        pengeluaranPerKategori: value.pengeluaranPerKategori,
        transaksi: from_candid_vec_n20(_uploadFile, _downloadFile, value.transaksi),
        totalPemasukan: value.totalPemasukan,
        bulan: value.bulan,
        pendapatanBersih: value.pendapatanBersih
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    userId: [] | [Principal];
    jumlahPembayaran: [] | [bigint];
    waktuTransaksi: _Time;
    waktuPencatatan: _Time;
    tanggalTransaksi: _Time;
    kembalian: [] | [bigint];
    items: Array<_Transaksi>;
}): {
    total: bigint;
    userId?: Principal;
    jumlahPembayaran?: bigint;
    waktuTransaksi: Time;
    waktuPencatatan: Time;
    tanggalTransaksi: Time;
    kembalian?: bigint;
    items: Array<Transaksi>;
} {
    return {
        total: value.total,
        userId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.userId)),
        jumlahPembayaran: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.jumlahPembayaran)),
        waktuTransaksi: value.waktuTransaksi,
        waktuPencatatan: value.waktuPencatatan,
        tanggalTransaksi: value.tanggalTransaksi,
        kembalian: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.kembalian)),
        items: value.items
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pengeluaran: Array<_Pengeluaran>;
    totalPengeluaran: bigint;
    transaksi: Array<_TransaksiSelesai>;
    totalPemasukan: bigint;
    pendapatanBersih: bigint;
}): {
    pengeluaran: Array<Pengeluaran>;
    totalPengeluaran: bigint;
    transaksi: Array<TransaksiSelesai>;
    totalPemasukan: bigint;
    pendapatanBersih: bigint;
} {
    return {
        pengeluaran: from_candid_vec_n10(_uploadFile, _downloadFile, value.pengeluaran),
        totalPengeluaran: value.totalPengeluaran,
        transaksi: from_candid_vec_n20(_uploadFile, _downloadFile, value.transaksi),
        totalPemasukan: value.totalPemasukan,
        pendapatanBersih: value.pendapatanBersih
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pengeluaran>): Array<Pengeluaran> {
    return value.map((x)=>from_candid_Pengeluaran_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransaksiSelesai>): Array<TransaksiSelesai> {
    return value.map((x)=>from_candid_TransaksiSelesai_n21(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
